language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '14'
install:
  - npm install -g codecov
  - npm install
after_success:
  - npm run codecov
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
